version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: ecoforums-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecoforums
    ports:
      - "5436:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always

volumes:
  db-data:
